spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monitoringsystem
    username: root
    password: hxy116991
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8182
